"""add_status_deleted_at_ttyd_fields

Revision ID: 56882cb35a0c
Revises: a881b443a62c
Create Date: 2025-08-17 16:06:44.271900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56882cb35a0c'
down_revision: Union[str, Sequence[str], None] = 'a881b443a62c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vms', sa.Column('task_id', sa.String(), nullable=False))
    op.add_column('vms', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('vms', sa.Column('deletion_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vms', 'deletion_reason')
    op.drop_column('vms', 'deleted_at')
    op.drop_column('vms', 'task_id')
    # ### end Alembic commands ###
