"""update_status_field

Revision ID: 6b45a7fe415e
Revises: 56882cb35a0c
Create Date: 2025-08-17 16:26:06.017949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b45a7fe415e'
down_revision: Union[str, Sequence[str], None] = '56882cb35a0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vms', sa.Column('status', sa.String(), nullable=True))
    op.drop_column('vms', 'deletion_reason')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vms', sa.Column('deletion_reason', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('vms', 'status')
    # ### end Alembic commands ###
