"""add_ip_addres

Revision ID: ea2cc19a62d1
Revises: ee4f4075518d
Create Date: 2025-07-26 13:34:37.729471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea2cc19a62d1'
down_revision: Union[str, Sequence[str], None] = 'ee4f4075518d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vms', sa.Column('ip_addres', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vms', 'ip_addres')
    # ### end Alembic commands ###
