dbfilename redis_queue.rdb
dir /home/nastya/Frappe-local/config/pids
pidfile /home/nastya/Frappe-local/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /home/nastya/Frappe-local/config/redis_queue.acl
